# Generated by Django 5.1.1 on 2024-09-25 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiegeSocial",
            fields=[
                (
                    "local_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="high_level.local",
                    ),
                ),
            ],
            bases=("high_level.local",),
        ),
    ]
