# Generated by Django 5.1.1 on 2024-09-25 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0004_etape_produit_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="etape_suivant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="high_level.etape"
            ),
        ),
    ]
