# Generated by Django 5.1.1 on 2024-10-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("high_level", "0007_remove_stock_objet_stock_ressource_usine_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etape",
            name="etape_suivant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="high_level.etape",
            ),
        ),
    ]
